### ISSUE TITLE
Need to update pip installation

### ISSUE THREAD

**Issue by seanchung2** [Microsoft/MMdnn#16]
When I tried to update my MMdnn by `pip install -U https://github.com/Microsoft/MMdnn/releases/download/0.1.1/mmdnn-0.1.1-py2.py3-none-any.whl
`, it didn't update the version in master now.

For the `setup.py`, I tried it but it looked like I have to add some command after it
```
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```
And if I use `pip install git+https://github.com/Microsoft/MMdnn.git@master`, there will be an encoding error:
```
Collecting git+https://github.com/Microsoft/MMdnn.git@master
  Cloning https://github.com/Microsoft/MMdnn.git (to master) to /tmp/pip-UM6BrV-build
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-UM6BrV-build/setup.py", line 5, in <module>
        with open('README.md', encoding='utf-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function
```

Can you please explain the usage or update it?
Thanks.

**Comment by kitstar** [comment]
Hi @seanchung2  There is a big change for padding format, but the MXNet part has not been finished. So I didn't release the new pip package. Better way is clone the master to use the source code way. We will update the pip as soon as the MXNet part finish.

And the 'encoding' error is caused by    in python3  function open() can take encoding type but python2 can not.
