### ISSUE TITLE
Boost.Python.ArgumentError

### ISSUE THREAD

**Issue by yorkjohn** [Microsoft/MMdnn#186]
Platform (like ubuntu 16.04/win10): ubuntu 16.04

Python version:2.7

Source framework with version (like Tensorflow 1.4.1 with GPU):Tensorflow with GPU

Destination framework with version (like CNTK 2.3 with GPU):caffe with GPU

transfer model from TF to caffe has this error.
This issue has been aroused in the closed topic " Trouble Converting IR to Caffe #111 "
it can be solved using str() method.
However, when converting straight from TF to caffe, same problem occurs when the inter-media py file is 
created. For example: mmconvert -sf tensorflow -in vgg16.ckpt.meta -iw vgg16.ckpt -df caffe --dstNodeName MMdnn_Output -om ./vgg16_TF2caffe

**Comment by JiahaoYao** [comment]
Platform : MacOS 10.13.3

Python version:2.7

@yorkjohn 
I think it can be still solved by using str() method. 

In `mmdnn/conversion/caffe/saver.py`, I add in Line 7-8
``` python
    dump_net = str(dump_net)
    dump_weight = str(dump_weight)
```

The code crashes because in  `model = caffe.Net(dump_net, dump_weight, caffe.TEST)`, `dump_net` and `dump_weight` are 'unicode' not 'str'. It works after converted to `str`. This problem is also mentioned in [Caffe Issue #3220](https://github.com/BVLC/caffe/issues/3220). 

I will provide pull request soon to solve this problem.
