### ISSUE TITLE
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file ./model.ckpt-10.data-00000-of-00001: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?

### ISSUE THREAD

**Issue by karimhasebou** [Microsoft/MMdnn#217]
Platform: Ubuntu 18.04

Python version: 2.7

Source framework with version tensorflow 1.8 cpu

Destination framework with version IR representation:

Pre-trained model path (webpath or webdisk path)

[model.ckpt-10.zip](https://github.com/Microsoft/MMdnn/files/2047848/model.ckpt-10.zip)

Running scripts:
mmtoir -f tensorflow -d mnist_cnn -w model.ckpt-10.data-00000-of-00001 -n model.ckpt-10.meta  --dstNodeName dense

**Comment by karimhasebou** [comment]
The model used here is one from https://www.tensorflow.org/tutorials/layers

**Comment by JiahaoYao** [comment]
Two things have to be pointed out.
1. the error is raised because of `ckpt` file. You can refer to [Restoring Tensorflow Models](https://orvillemcdonald.com/2018/02/13/restoring-tensorflow-models/). To be brief, you should use `-w model.ckpt-10` instead of `-w model.ckpt-10.data-00000-of-00001`. This way, it will also read the `-w model.ckpt-10.index`.
2. The `dense` might not your model node. You can visualize the model graph easily with `mmvismeta model.ckpt-10.meta ./logs/`. For me, I probably choose the `dense_1/BiasAdd`, which can be seen more clearly from the graph below.

![image](https://user-images.githubusercontent.com/20907377/40719186-48227e42-6445-11e8-8c65-e6d0c05b648b.png)

**Comment by Rajamohanreddyai** [comment]
Hello all, just follow the below video and export your own model with in a 10 seconds

https://youtu.be/w0Ebsbz7HYA﻿

**Comment by chamecall** [comment]
I fount a solution [here](https://orvillemcdonald.com/2018/02/13/restoring-tensorflow-models/).
