### ISSUE TITLE
ValueError: too many values to unpack (expected 2)

### ISSUE THREAD

**Issue by lucasncabral** [microsoft/MMdnn#759]
I am using the MMdnn docker image to try to convert my caffe model to tensorflow. I followed the following steps:

**1.** I imported my model into the container.
**2.** Convert my model from Caffe to IR (Caffe -> IR):
`mmtoir -f caffe -n deploy.prototxt -w model.caffemodel -o caffe_resnet_IR
`

result:

```
IR network structure is saved as [caffe_resnet_IR.json].
IR network structure is saved as [caffe_resnet_IR.pb].
IR weights are saved as [caffe_resnet_IR.npy].
```

**3.** Convert my model from IR to Tensorflow code snippet:
`mmtocode -f tensorflow --IRModelPath caffe_resnet_IR.pb --IRWeightPath caffe_resnet_IR.npy --dstModelPath tf_resnet.py`

result: 

```
Parse file [caffe_resnet_IR.pb] with binary format successfully.
Target network code snippet is saved as [tf_resnet.py].
```

**4.** After generating the Tensorflow code snippet, i try convert the Tensorflow code snippet and IR weights file to Tensorflow original model:

`mmtomodel -f tensorflow -in tf_resnet.py -iw caffe_resnet_IR.npy -o tf_resnet --dump_tag SERVING`

result:

```
Traceback (most recent call last):
  File "/ usr / local / bin / mmtomodel", line 11, in <module>
    sys.exit (_main ())
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/dump_code.py", line 78, in _main
    ret = dump_code (args.framework, args.inputNetwork, args.inputWeight, args.outputModel, args.dump_tag)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/_script/dump_code.py", line 24, in dump_code
    save_model (MainModel, network_filepath, weight_filepath, dump_filepath, dump_tag)
  File "/usr/local/lib/python3.5/dist-packages/mmdnn/conversion/tensorflow/saver.py", line 9, in save_model
    input, model = MainModel.KitModel (weight_filepath)
ValueError: Too many values ​​to unpack (expected 2)
```

Am I skipping any steps?

**Comment by SmokerX** [comment]
Hi~, could you give me your caffe model file? You can save the file to a cloud disk and send me a link, or send the file directly to my mailbox（524058708@qq.com）.

**Comment by lucasncabral** [comment]
@SmokerX I sent it to your mailbox.

**Comment by SmokerX** [comment]
The reason for this problem is because you have a problem with the original model.
In the file tf_resnet.py , you can clearly see that there are three return values in the KitModel method, and the place you gave the error only hopes to have 2, which is the direct cause of the error.

As for why this file will generate 3 return values, because this piece of logic, in the file MMdnn\mmdnn\conversion\common\DataStructure\graph.py
`    def _make_output_layers(self):
        for name, layer in self.layer_map.items():
            if len(layer.out_edges) == 0:
                self.output_layers.append(name)`

In your model, both prob1 and conv4_2 meet this condition, so they are added as output nodes.


So now you have the following solutions:
1. Modify your original model so that only one useful output is preserved (prob1 or conv4_2)
2. Modify the intermediate file tf_resnet.py to change the return value of the KitModel method to 2 (ie delete one in prob1 or conv4_2)
3. Modify the source code so that it supports multiple outputs.

As for which one to choose, you decide for yourself.

**Comment by SmokerX** [comment]
@lucasncabral 
I fixed this bug in [](https://github.com/microsoft/MMdnn/pull/766)
