### ISSUE TITLE
How do I change the port for mmvismeta

### ISSUE THREAD

**Issue by mylyu** [microsoft/MMdnn#796]
It seems always using port 6006, which is forbidden in my server. How to change it?

**Comment by linmajia** [comment]
@mylyu , thank you very much for the feedback. 6006 is the default port used by TensorBoard, and you may take the following workaround:
1. Go to the installation directory of MMdnn. E.g. ~/.local/lib/pythonX.Y/site-packages/mmdnn , or /usr/lib/python3/dist-packages/mmdnn
2. Open file "mmdnn/conversion/examples/tensorflow/vis_meta.py" .
3. Locate the code "os.system("tensorboard --logdir=" + sys.argv[2])" . It should be at line 37.
4. Suppose that you will use port 6008, then add "--port=6008" before "--logdir".

Please have a try and verify whether the issue is fixed.

Thanks.

**Comment by mylyu** [comment]
thanks for your help, I will try.

**Comment by linmajia** [comment]
@mylyu , we have submitted code to the master branch which improves mmvismeta. Please refer to the pull request https://github.com/microsoft/MMdnn/pull/802:
1. Add explicit argument names for checkpoint meta file and log directory.
2. Support passing extra TensorBoard arguments.
