### ISSUE TITLE
'mmdownload' is not an internal or external command, nor is it a running program or batch file.

### ISSUE THREAD

**Issue by shiningdsr** [microsoft/MMdnn#852]
Platform (like ubuntu 16.04/win10):win10

Python version:3.7.7

Source framework with version (like Tensorflow 1.4.1 with GPU):Tensorflow 1.13.1 with GPU

Destination framework with version (like CNTK 2.3 with GPU):Keras

Pre-trained model path (webpath or webdisk path):

Running scripts: When I execute the command "mmdownload -f keras -n resnet50" I got an error report as follows:
'mmdownload' is not an internal or external command, nor is it a running program or batch file.
I have checked that I have installed mmdnn successfully . Is there any similar issues, or one knows why?  Thanks very much!

**Comment by linmajia** [comment]
@shiningdsr , thank you very much for the feedback. I guess it is because the parent directory of mmdownload is not in the %Path% environment variable:
1. You installed MMdnn into the Python's system site. Supposing that your Python 3.7 is in "c:\Python37", mmdownload should be in "c:\Python37\Scripts" .
2. You installed MMdnn into the Python's user site. Run "python3 -m site", and mmdownload should be in "USER_BASE\Scripts" .

**Comment by shiningdsr** [comment]
Thank you so much for your answer, I have solved this problem,it is just because I didn't install mmdnn successfully,in other words,several packages failed when I install mmdnn.And after I installed mmdnn again, all problems disappeared.



---Original---
